### ISSUE TITLE
filename.css.map doesn't generated

### ISSUE THREAD

**Issue by xcatliu** [postcss/postcss-cli#155]
My `postcss.config.js`:

```js
module.exports = {
    plugins: [
        require('postcss-import')(),
        require('postcss-cssnext')(),
        require('cssnano')({
            preset: 'default',
        }),
    ],
    map: {
        inline: false
    }
};
```

After exec `postcss src/*.css --dir dist/`, there are only one file `filename.css` generated:

```css
body{color:#333}
/*# sourceMappingURL=filename.css.map */
```

There is no `filename.css.map` file.
