### ISSUE TITLE
Postcss fails with CssSyntaxError Unclosed string for valid strings

### ISSUE THREAD

**Issue by bduisenov** [postcss/postcss-cli#199]
Hi, I'm trying to run postcss-cli 5 with bootstrap4 and facing an issue with the error telling that the string is unclosed, but it is a valid string. Here's an excerpt:

```sh
Error: EAGAIN: resource temporarily unavailable, write
CssSyntaxError: /app/app.css:2473:25: Unclosed string

  2471 |
  2472 | .custom-checkbox .custom-control-input:checked ~ .custom-control-label::after {
> 2473 |   background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'%3E%3Cpath fill='%23fff' d='M6.564.75l-3.59 3.612-1.538-1.55L0 4.26 2.974 7.25 8 2.1
       |                         ^
```

I assume that postcss fails because of nested quotes which are inside of the string.
I created repo showing where you can reproduce this error. https://github.com/bduisenov/postcss_bootstrap_4

Could you give a hint what it might be?

**Comment by RyanZim** [comment]
This must be a bug in postcss itself ping @ai

**Comment by ai** [comment]
@bduisenov can you give the whole love of CSS at 2473

**Comment by bduisenov** [comment]
@ai  sure
```sh
 2472  .custom-checkbox .custom-control-input:checked ~ .custom-control-label::after {
 2473    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'%3E%3Cpath fill='%23fff' d='M6.564.75l-3.59 3.612-1.538-1.55L0 4.26 2.974 7.25 8 2.193z'/%3E%3C/svg%3E"); }
```

**Comment by RyanZim** [comment]
@ai Did you get to look at this?

**Comment by ai** [comment]
Not it is parsing without problems.

**Comment by astorije** [comment]
Hi there!

I am in the same boat, running `postcss-cli` on Bootstrap v4 and hitting a similar issue:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EAGAIN: resource temporarily unavailable, write
CssSyntaxError: .../dist/index.css:2084:103: Unclosed bracket

  2082 |     background-color: #17a2b8;
  2083 |     border-color: #17a2b8; }
> 2084 |     .btn-outline-info:not(:disabled):not(.disabled):active:focus, .btn-outline-info:not(:disabled):not(.d
```

The whole line is:

```css
    .btn-outline-info:not(:disabled):not(.disabled):active:focus, .btn-outline-info:not(:disabled):not(.disabled).active:focus,
```

And the whole section around this line:

<details>

```css
.btn-outline-info {
  color: #17a2b8;
  background-color: transparent;
  background-image: none;
  border-color: #17a2b8; }
  .btn-outline-info:hover {
    color: #fff;
    background-color: #17a2b8;
    border-color: #17a2b8; }
  .btn-outline-info:focus, .btn-outline-info.focus {
    box-shadow: 0 0 0 0.2rem rgba(23, 162, 184, 0.5); }
  .btn-outline-info.disabled, .btn-outline-info:disabled {
    color: #17a2b8;
    background-color: transparent; }
  .btn-outline-info:not(:disabled):not(.disabled):active, .btn-outline-info:not(:disabled):not(.disabled).active,
  .show > .btn-outline-info.dropdown-toggle {
    color: #fff;
    background-color: #17a2b8;
    border-color: #17a2b8; }
    .btn-outline-info:not(:disabled):not(.disabled):active:focus, .btn-outline-info:not(:disabled):not(.disabled).active:focus,
    .show > .btn-outline-info.dropdown-toggle:focus {
      box-shadow: 0 0 0 0.2rem rgba(23, 162, 184, 0.5); }
```

</details>

A couple additional details:

- The whole build step is:
  ```
  node-sass src/scss/index.scss | postcss --use autoprefixer --output dist/index.css
  ```
- It doesn't fail _all the time_. 1 time out of 5-ish, it does pass.
- When I generate a temp file instead of piping, it always passes:
  ```
  node-sass src/scss/index.scss dist/index.foo.css && postcss dist/index.foo.css --use autoprefixer --output dist/index.css
  ```
- I don't believe this has anything to do with that line, because I made a dummy change (I forget what, but something like removing an empty line or something) and it gave me a different error (`index.css:2125:23: Missed semicolon`).
